version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: search_term_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: